package com.lh.entity;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.d_id
     *
     * @mbggenerated Fri Apr 06 13:02:57 CST 2018
     */
    private Long dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.d_name
     *
     * @mbggenerated Fri Apr 06 13:02:57 CST 2018
     */
    private String dName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.d_id
     *
     * @return the value of t_dept.d_id
     *
     * @mbggenerated Fri Apr 06 13:02:57 CST 2018
     */
    public Long getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.d_id
     *
     * @param dId the value for t_dept.d_id
     *
     * @mbggenerated Fri Apr 06 13:02:57 CST 2018
     */
    public void setdId(Long dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.d_name
     *
     * @return the value of t_dept.d_name
     *
     * @mbggenerated Fri Apr 06 13:02:57 CST 2018
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.d_name
     *
     * @param dName the value for t_dept.d_name
     *
     * @mbggenerated Fri Apr 06 13:02:57 CST 2018
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }
}